version: "3"

x-environment: &environment
  AMQP_DSN: amqp://guest:guest@rabbitmq:5672/
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: 5672
  REDIS_DSN: redis://redis:6379
  REDIS_HOST: redis
  REDIS_PORT: 6379

services:
  backend:
    build: backend
    ports:
      - "3000:3000"
    environment:
      <<: *environment
      PORT: 3000
      NODE_ENV: production
  worker:
    build: worker
    environment:
      <<: *environment
  rabbitmq:
    image: rabbitmq:3.9.9-management-alpine
    expose:
      - 5672
      #- 15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  redis:
    image: redis:alpine
    expose:
      - 6379
    #ports:
    #  - '6379:6379'